/**
 * Shared transactional email sender (Brevo).
 * HTML is generated by React Email components in lib/notifications/emails/.
 */

/** Parse `NOTIFY_FROM_EMAIL` — accepts `"Name <email>"` or a bare `email`. */
function parseSender(raw: string): { email: string; name?: string } {
  const m = raw.match(/^\s*(.*?)\s*<\s*(.+?)\s*>\s*$/)
  if (m) return { name: m[1] || undefined, email: m[2] }
  return { email: raw.trim() }
}

/**
 * The mailbox an address actually reaches, for comparison only.
 *
 * Testing a booking flow means booking repeatedly, and the same address cannot
 * be reused, so the addresses in play are ikim+hv@, ikim+jkv@, and however many
 * more get invented next. They all land in one inbox. Matching them literally
 * would mean adding each one to the allowlist before it can be used, which
 * defeats the point of plus-addressing entirely.
 *
 * Stripping the +tag cannot widen who is reachable: mail to name+anything@ goes
 * to whoever owns name@, so if that mailbox is listed, its tags are already the
 * same person. Gmail also ignores dots in the local part, so those go too — but
 * only for Gmail, where it is true.
 *
 * Used to compare, never to send. The recipient keeps the address as written.
 *
 * Exported for its tests. This is the piece where a mistake is silent — too
 * loose and a real customer receives a test mail, too strict and nothing
 * arrives and the guard looks broken.
 */
export function canonicalAddress(email: string): string {
  const trimmed = email.trim().toLowerCase()
  const at = trimmed.lastIndexOf("@")
  if (at < 1) return trimmed

  const local = trimmed.slice(0, at).split("+")[0]
  const domain = trimmed.slice(at + 1)
  const canonicalDomain = domain === "googlemail.com" ? "gmail.com" : domain
  const canonicalLocal =
    canonicalDomain === "gmail.com" ? local.replace(/\./g, "") : local

  return `${canonicalLocal}@${canonicalDomain}`
}

/**
 * Recipients this environment is allowed to mail, if it is restricted.
 *
 * The dev clone is a copy of production, real addresses and all, and it is
 * pointed at the same Brevo account — so a test cancellation there would mail a
 * real customer from noreply@thewellnesskorea.com. Setting EMAIL_ALLOWLIST on
 * such an environment keeps mail flowing to the people testing and drops the
 * rest loudly.
 *
 * Absent means no restriction, so production is unaffected. Present but empty
 * means nobody — not everybody. The difference matters: this is configured by
 * hand in a dashboard, and a value that fails to save, or saves blank, would
 * otherwise turn the guard off silently on the one environment that needs it.
 * Failing closed there costs a confused "why no mail", which the log answers.
 *
 * If mail ever goes missing, the skip is logged with the variable's name in it.
 */
export function allowedRecipients(
  emails: string[],
  context: string,
): string[] {
  const raw = process.env.EMAIL_ALLOWLIST
  if (raw === undefined) return emails
  if (!raw.trim()) {
    console.warn(
      `[${context}] EMAIL_ALLOWLIST is set but empty — sending to nobody`,
    )
    return []
  }

  const allowed = raw.split(",").map(canonicalAddress).filter(Boolean)
  const kept = emails.filter((e) => allowed.includes(canonicalAddress(e)))
  const dropped = emails.filter((e) => !kept.includes(e))

  if (dropped.length > 0) {
    console.warn(
      `[${context}] EMAIL_ALLOWLIST is set — not sending to ${dropped.join(", ")}`,
    )
  }
  return kept
}

export async function sendEmail(
  to: string | string[],
  subject: string,
  html: string,
  context = "email",
): Promise<void> {
  const apiKey = process.env.BREVO_API_KEY
  const from = process.env.NOTIFY_FROM_EMAIL

  if (!apiKey || !from) {
    console.warn(
      `[${context}] BREVO_API_KEY or NOTIFY_FROM_EMAIL missing — skipping send`,
    )
    return
  }

  const addresses = allowedRecipients(
    Array.isArray(to) ? to : [to],
    context,
  )
  if (addresses.length === 0) return

  const recipients = addresses.map((email) => ({ email }))

  const res = await fetch("https://api.brevo.com/v3/smtp/email", {
    method: "POST",
    headers: {
      "api-key": apiKey,
      "content-type": "application/json",
      accept: "application/json",
    },
    body: JSON.stringify({
      sender: parseSender(from),
      to: recipients,
      subject,
      htmlContent: html,
    }),
  })

  if (!res.ok) {
    const body = await res.text()
    console.error(`[${context}] send failed: ${res.status}`, body)
    throw new Error(`Failed to send email (${context}).`)
  }
}
