/**
 * Shared transactional email sender (Brevo).
 * HTML is generated by React Email components in lib/notifications/emails/.
 */

/** Parse `NOTIFY_FROM_EMAIL` — accepts `"Name <email>"` or a bare `email`. */
function parseSender(raw: string): { email: string; name?: string } {
  const m = raw.match(/^\s*(.*?)\s*<\s*(.+?)\s*>\s*$/)
  if (m) return { name: m[1] || undefined, email: m[2] }
  return { email: raw.trim() }
}

/**
 * Recipients this environment is allowed to mail, if it is restricted.
 *
 * The dev clone is a copy of production, real addresses and all, and it is
 * pointed at the same Brevo account — so a test cancellation there would mail a
 * real customer from noreply@thewellnesskorea.com. Setting EMAIL_ALLOWLIST on
 * such an environment keeps mail flowing to the people testing and drops the
 * rest loudly.
 *
 * Unset means no restriction, so production is unaffected. If mail ever goes
 * missing, the skip is logged with the variable's name in it.
 */
function allowedRecipients(
  emails: string[],
  context: string,
): string[] {
  const raw = process.env.EMAIL_ALLOWLIST
  if (!raw?.trim()) return emails

  const allowed = raw
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean)
  const kept = emails.filter((e) => allowed.includes(e.trim().toLowerCase()))
  const dropped = emails.filter((e) => !kept.includes(e))

  if (dropped.length > 0) {
    console.warn(
      `[${context}] EMAIL_ALLOWLIST is set — not sending to ${dropped.join(", ")}`,
    )
  }
  return kept
}

export async function sendEmail(
  to: string | string[],
  subject: string,
  html: string,
  context = "email",
): Promise<void> {
  const apiKey = process.env.BREVO_API_KEY
  const from = process.env.NOTIFY_FROM_EMAIL

  if (!apiKey || !from) {
    console.warn(
      `[${context}] BREVO_API_KEY or NOTIFY_FROM_EMAIL missing — skipping send`,
    )
    return
  }

  const addresses = allowedRecipients(
    Array.isArray(to) ? to : [to],
    context,
  )
  if (addresses.length === 0) return

  const recipients = addresses.map((email) => ({ email }))

  const res = await fetch("https://api.brevo.com/v3/smtp/email", {
    method: "POST",
    headers: {
      "api-key": apiKey,
      "content-type": "application/json",
      accept: "application/json",
    },
    body: JSON.stringify({
      sender: parseSender(from),
      to: recipients,
      subject,
      htmlContent: html,
    }),
  })

  if (!res.ok) {
    const body = await res.text()
    console.error(`[${context}] send failed: ${res.status}`, body)
    throw new Error(`Failed to send email (${context}).`)
  }
}
