/**
 * Shared transactional email sender (Brevo).
 * HTML is generated by React Email components in lib/notifications/emails/.
 */

/** Parse `NOTIFY_FROM_EMAIL` — accepts `"Name <email>"` or a bare `email`. */
function parseSender(raw: string): { email: string; name?: string } {
  const m = raw.match(/^\s*(.*?)\s*<\s*(.+?)\s*>\s*$/)
  if (m) return { name: m[1] || undefined, email: m[2] }
  return { email: raw.trim() }
}

export async function sendEmail(
  to: string | string[],
  subject: string,
  html: string,
  context = "email",
): Promise<void> {
  const apiKey = process.env.BREVO_API_KEY
  const from = process.env.NOTIFY_FROM_EMAIL

  if (!apiKey || !from) {
    console.warn(
      `[${context}] BREVO_API_KEY or NOTIFY_FROM_EMAIL missing — skipping send`,
    )
    return
  }

  const recipients = (Array.isArray(to) ? to : [to]).map((email) => ({ email }))

  const res = await fetch("https://api.brevo.com/v3/smtp/email", {
    method: "POST",
    headers: {
      "api-key": apiKey,
      "content-type": "application/json",
      accept: "application/json",
    },
    body: JSON.stringify({
      sender: parseSender(from),
      to: recipients,
      subject,
      htmlContent: html,
    }),
  })

  if (!res.ok) {
    const body = await res.text()
    console.error(`[${context}] send failed: ${res.status}`, body)
    throw new Error(`Failed to send email (${context}).`)
  }
}
