/**
 * Shared Resend email sender.
 * HTML is generated by React Email components in lib/notifications/emails/.
 */
export async function sendResendEmail(
  to: string,
  subject: string,
  html: string,
  context = "email",
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY
  const from = process.env.NOTIFY_FROM_EMAIL

  if (!apiKey || !from) {
    console.warn(`[${context}] RESEND_API_KEY or NOTIFY_FROM_EMAIL missing — skipping send`)
    return
  }

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ from, to, subject, html }),
  })

  if (!res.ok) {
    const body = await res.text()
    console.error(`[${context}] send failed: ${res.status}`, body)
    throw new Error(`Failed to send email (${context}).`)
  }
}
