-- Convert journal seed bodies from Markdown to TipTap HTML (body_en column unchanged).
-- Safe after 014/015; updates by slug. Source: lib/journal/seed-content.ts

update public.journal_posts set
  body_en = '<p>Korean culture has long understood that a life well lived is not faster, but clearer. Empty the mind. Awaken the body. Craft with care. Nourish with what the season offers. Savor the moment—including the quiet joy of gathering.</p><p>We call this rhythm the five paths: Bium (stillness), Kkaeum (movement), Jieum (craft), Chaeum (nourishment), and Nurim (joy). They are not separate wellness trends. They are one continuous breath.</p><blockquote><p>We do not promise transformation in an hour. We offer practices that help time feel wider—not stolen back, but lived.</p></blockquote><h2>Why a platform, not a single studio</h2><p>The Wellness Korea begins at Brickwell in Seochon, but it is not limited to one address. Spaces hold daily life. Journeys will carry you to regions where the land itself teaches pace. This Journal holds the stories that connect them—philosophy, places, people, and the taste of a particular season.</p><p>If you are new here, meet a Wellness Guide on the homepage, browse the schedule, and return when you want the longer view.</p>'
where slug = 'live-the-time-more-fully';

update public.journal_posts set
  body_en = '<p>Seochon does not perform for visitors. Laundry lines cross narrow lanes. An elder passes with a market bag. Somewhere a gate opens onto a courtyard where light pools differently than on the main road. Brickwell takes its name from the well at the center of that courtyard—a place to draw water, pause, and continue.</p><p>We built four floors not to fill every hour, but to hold distinct tones: movement on the lower levels, meditation and breath above, sound and smaller gatherings higher still. Sessions begin and end with margin. Arrival should feel like stepping out of the city''s hurry, not into another queue.</p><h2>What you will find on the schedule</h2><p>Classes are led by Wellness Guides and Artists who live these paths in their work—yoga and breath, meditation, gugak and Korean dance, tea and seasonal conversation. The schedule on our homepage shows what is confirmed and open for booking; it changes week by week, as living spaces do.</p><h2>A showroom, not a spectacle</h2><p>Brickwell is where our philosophy becomes sensory: plaster walls, natural light, the sound of a class ending while the next guest waits without impatience. Partners in food and craft will appear here over time—not as retail shelves, but as stories told in the same room as a morning class.</p><p>If you are planning a visit, start with the schedule. The courtyard will be here when you arrive.</p>'
where slug = 'brickwell-seochon-space';

update public.journal_posts set
  body_en = '<p>Jeju is often photographed from above: a green island in a blue sea. That image is true and incomplete. To know Jeju you must walk at the speed of its stone walls—low, patient, built to turn wind rather than fight it.</p><p>In late winter the citrus groves carry a sweetness sharpened by cold nights. Mist sits in the caldera of an oreum long after the sun has cleared the coast. A guest who rises early might hear only their boots on volcanic path and the distant sea—not silence as absence, but silence as room to think.</p><blockquote><p>Local tourism, for us, is attention. Not how many places you tick off, but how deeply one place allows you to breathe.</p></blockquote><h2>What we look for in a regional Journey</h2><p>When The Wellness Korea travels beyond Seoul, we ask the same questions we ask of Brickwell: Does the land suggest a pace? Is there a craft, a meal, or a sound that belongs only here? Can a Wellness Guide and an Artist hold a program that would feel wrong anywhere else?</p><p>On Jeju that might mean a morning walk along a low oreum, tea with someone who knows which hillside was picked after the first frost, and an evening where gugak responds to the rhythm of the coast—not as background music, but as conversation with place.</p><h2>Not yet on the calendar</h2><p>Our first Jeju Journey is still taking shape. When dates open, they will appear alongside Brickwell on the homepage. Until then, this is the view from the path: why we care about regions at all, and why we will not rush a program that is not ready.</p><p>If Jeju is already calling to you, begin with stillness at home. The island will wait without impatience.</p>'
where slug = 'slow-mornings-on-jeju';

update public.journal_posts set
  body_en = '<p>A bowl of doenjang jjigae carries months in an earthenware jar—soybeans transformed by hands that check the ferment each day, not because a label demands it, but because the jar tells them when. A spring green tea carries a hillside and a rain pattern you will never see on the package.</p><p>We do not talk about &quot;clean eating&quot; as punishment. We talk about nourishment as Chaeum—one of the five paths—where what you take in supports the rhythm of the day you are trying to live.</p><h2>Taste at Brickwell</h2><p>In our Space, food appears slowly and deliberately: tea before or after class, seasonal small plates that change with what growers bring, conversations that begin at a table and continue in the Journal. A partner who joins Brickwell is not renting shelf space. They are joining a story—region, season, and the hands that waited.</p><h2>What we publish under Local Taste</h2><p>Here you will read about makers we trust: a brewery in Gangwon that ages on mountain air, a tea house that harvests once and speaks of that year for months, a baker who ferments dough the way others meditate. We name them when the relationship is real, not when a press release arrives.</p><blockquote><p>Good food, like good wellness, cannot be rushed. The same is true of good partnership.</p></blockquote><p>When you visit Brickwell, taste what is on offer that week. When you travel, carry these stories to the regions they describe. That is how offline and online stay one thread—not commerce first, but care first.</p>'
where slug = 'season-and-ferment';
