-- Record on-site payments in the payments table.
--
-- Only create_booking_hold wrote payment rows, so classes paid at the studio
-- left no trace of money owed or collected: revenue for every non-USD class
-- was invisible, and nothing knew whether the customer had actually paid.
--
-- An on-site payment is the same thing as an online one — same booking, same
-- amount, same currency — differing only in when and how it is collected. So
-- it belongs in the same table rather than a parallel record that would drift.
-- The existing columns already fit: status goes pending -> paid, and
-- merchant_uid is generated by us rather than by a PG, so nothing changes
-- structurally.
--
-- Free classes deliberately get no row. There is nothing to collect, so the
-- row would never change state, and its absence becomes meaningful: no
-- payment row now means free, rather than "free or on-site, unknowable".

create or replace function public.create_booking(
  p_session_id uuid,
  p_guest_name text,
  p_guest_email text,
  p_guest_phone text default null,
  p_user_id uuid default null,
  p_coupon_code text default null
)
returns table(booking_id uuid, cancel_token text)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_session public.sessions%rowtype;
  v_email text;
  v_booking_id uuid;
  v_cancel_token text;
  v_amount numeric;
  v_coupon record;
  -- A plpgsql record stays unassigned until a SELECT INTO touches it, and
  -- reading a field of an unassigned record raises. Without a separate flag,
  -- every booking made WITHOUT a coupon fails at the redemption check.
  v_has_coupon boolean := false;
begin
  v_email := public.normalize_email(p_guest_email);

  if v_email = '' or trim(p_guest_name) = '' then
    raise exception 'Name and email are required.';
  end if;

  select * into v_session from public.sessions where id = p_session_id for update;

  if not found then
    raise exception 'Session not found.';
  end if;

  if v_session.status <> 'confirmed' or not v_session.is_published then
    raise exception 'Session is not available for booking.';
  end if;

  if v_session.starts_at <= now() then
    raise exception 'Session has already started or ended.';
  end if;

  v_amount := public.session_final_price(
    v_session.price_amount, v_session.price_currency,
    v_session.discount_type, v_session.discount_value
  );

  if nullif(btrim(coalesce(p_coupon_code, '')), '') is not null then
    select * into v_coupon
    from public.check_coupon(p_coupon_code, p_session_id, v_email, true);
    if not v_coupon.ok and v_coupon.reason is distinct from 'not_better' then
      raise exception 'Coupon cannot be used: %', v_coupon.reason;
    end if;
    if v_coupon.ok then
      v_has_coupon := true;
      v_amount := v_coupon.final_amount;
    end if;
  end if;

  if v_amount > 0 and v_session.price_currency = 'USD' then
    raise exception 'Online payment required. Use create_booking_hold instead.';
  end if;

  if v_session.booked_count >= v_session.capacity then
    raise exception 'Session is full.';
  end if;

  if exists (
    select 1 from public.bookings b
    where b.session_id = p_session_id
      and (b.status = 'confirmed' or public.is_booking_hold_active(b))
      and (b.guest_email = v_email or (p_user_id is not null and b.user_id = p_user_id))
  ) then
    raise exception 'You already have a booking for this session.';
  end if;

  insert into public.bookings (session_id, user_id, guest_name, guest_email, guest_phone)
  values (p_session_id, p_user_id, trim(p_guest_name), v_email, nullif(trim(p_guest_phone), ''))
  returning public.bookings.id, public.bookings.cancel_token
  into v_booking_id, v_cancel_token;

  if v_has_coupon then
    insert into public.coupon_redemptions
      (coupon_id, booking_id, user_id, email, amount_discounted)
    values
      (v_coupon.coupon_id, v_booking_id, p_user_id, v_email, v_coupon.discount_amount);
  end if;

  -- Money is owed but not yet collected: pending until an admin records it.
  if v_amount > 0 then
    insert into public.payments (
      booking_id, merchant_uid, pg_provider, amount, currency, status
    )
    values (
      v_booking_id,
      'twk-' || replace(gen_random_uuid()::text, '-', ''),
      'onsite',
      v_amount,
      v_session.price_currency,
      'pending'
    );
  end if;

  update public.sessions set booked_count = booked_count + 1 where id = p_session_id;

  return query select v_booking_id, v_cancel_token;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Recording collection
--
-- confirm_booking_payment cannot be reused: it requires the booking to be
-- pending_payment with an unexpired hold, which describes the online flow. An
-- on-site booking is confirmed the moment it is made, and the payment lands
-- later.
-- ---------------------------------------------------------------------------

create or replace function public.collect_onsite_payment(
  p_booking_id uuid,
  p_collected boolean default true
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_payment public.payments%rowtype;
begin
  if not public.is_admin_user() then
    raise exception 'Admin only.';
  end if;

  select * into v_payment
  from public.payments
  where booking_id = p_booking_id
    and pg_provider = 'onsite'
  order by created_at desc
  limit 1
  for update;

  if not found then
    raise exception 'No on-site payment for this booking.';
  end if;

  if p_collected then
    if v_payment.status = 'paid' then
      return; -- idempotent: collecting twice is not an error
    end if;
    if v_payment.status <> 'pending' then
      raise exception 'Payment is not pending.';
    end if;
    update public.payments
    set status = 'paid', paid_at = now()
    where id = v_payment.id;
  else
    -- Undo a mistaken entry rather than leaving it wrong.
    if v_payment.status <> 'paid' then
      raise exception 'Payment is not marked paid.';
    end if;
    update public.payments
    set status = 'pending', paid_at = null
    where id = v_payment.id;
  end if;
end;
$$;

comment on function public.collect_onsite_payment is
  'Admin records that an on-site payment was collected (or reverses it). Separate from confirm_booking_payment, which is the online capture path and expects a pending_payment booking with a live hold.';

revoke all on function public.collect_onsite_payment(uuid, boolean) from public;
revoke all on function public.collect_onsite_payment(uuid, boolean) from anon;
grant execute on function public.collect_onsite_payment(uuid, boolean)
  to authenticated, service_role;


-- ---------------------------------------------------------------------------
-- Same unassigned-record fix for the online path.
--
-- 038 introduced `if v_coupon.ok then` around the redemption insert in both
-- booking functions. A plpgsql record is unassigned until a SELECT INTO
-- touches it, and reading a field of one raises — so every booking made
-- WITHOUT a coupon failed. Coupon bookings were the only ones tested, which
-- is how it shipped.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.create_booking_hold(p_session_id uuid, p_guest_name text, p_guest_email text, p_guest_phone text DEFAULT NULL::text, p_user_id uuid DEFAULT NULL::uuid, p_pg_provider text DEFAULT 'portone'::text, p_hold_minutes integer DEFAULT 10, p_coupon_code text DEFAULT NULL::text)
 RETURNS TABLE(booking_id uuid, cancel_token text, merchant_uid text, amount numeric, expires_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_session public.sessions%rowtype;
  v_email text;
  v_booking_id uuid;
  v_cancel_token text;
  v_merchant_uid text;
  v_expires timestamptz;
  v_amount numeric;
  v_coupon record;
  v_has_coupon boolean := false;
begin
  v_email := public.normalize_email(p_guest_email);

  if v_email = '' or trim(p_guest_name) = '' then
    raise exception 'Name and email are required.';
  end if;

  if p_hold_minutes < 1 or p_hold_minutes > 60 then
    raise exception 'Hold minutes must be between 1 and 60.';
  end if;

  if trim(p_pg_provider) = '' then
    raise exception 'pg_provider is required.';
  end if;

  select * into v_session from public.sessions where id = p_session_id for update;

  if not found then
    raise exception 'Session not found.';
  end if;

  if v_session.status <> 'confirmed' or not v_session.is_published then
    raise exception 'Session is not available for booking.';
  end if;

  if v_session.starts_at <= now() then
    raise exception 'Session has already started or ended.';
  end if;

  v_amount := public.session_final_price(
    v_session.price_amount, v_session.price_currency,
    v_session.discount_type, v_session.discount_value
  );

  if nullif(btrim(coalesce(p_coupon_code, '')), '') is not null then
    select * into v_coupon
    from public.check_coupon(p_coupon_code, p_session_id, v_email, true);
    -- 'not_better' is not a failure: the class is already cheaper than the
    -- coupon would make it, so book at that price rather than refusing a
    -- customer who would have paid less anyway. Anything else is refused so
    -- they are not charged full price expecting a discount.
    if not v_coupon.ok and v_coupon.reason is distinct from 'not_better' then
      raise exception 'Coupon cannot be used: %', v_coupon.reason;
    end if;
    if v_coupon.ok then
      v_has_coupon := true;
      v_amount := v_coupon.final_amount;
    end if;
  end if;

  -- Guard on what is actually charged: a coupon can take this to zero, and a
  -- free class books through create_booking instead.
  if v_amount <= 0 then
    raise exception 'This session does not require online payment. Use create_booking instead.';
  end if;

  if v_session.booked_count >= v_session.capacity then
    raise exception 'Session is full.';
  end if;

  if exists (
    select 1 from public.bookings b
    where b.session_id = p_session_id
      and (b.status = 'confirmed' or public.is_booking_hold_active(b))
      and (b.guest_email = v_email or (p_user_id is not null and b.user_id = p_user_id))
  ) then
    raise exception 'You already have a booking for this session.';
  end if;

  v_expires := now() + make_interval(mins => p_hold_minutes);
  v_merchant_uid := 'twk-' || replace(gen_random_uuid()::text, '-', '');

  insert into public.bookings (
    session_id, user_id, guest_name, guest_email, guest_phone, status, expires_at
  )
  values (
    p_session_id, p_user_id, trim(p_guest_name), v_email,
    nullif(trim(p_guest_phone), ''), 'pending_payment', v_expires
  )
  returning public.bookings.id, public.bookings.cancel_token
  into v_booking_id, v_cancel_token;

  if v_has_coupon then
    insert into public.coupon_redemptions
      (coupon_id, booking_id, user_id, email, amount_discounted)
    values
      (v_coupon.coupon_id, v_booking_id, p_user_id, v_email, v_coupon.discount_amount);
  end if;

  insert into public.payments (
    booking_id, merchant_uid, pg_provider, amount, currency, status
  )
  values (
    v_booking_id, v_merchant_uid, trim(p_pg_provider),
    v_amount, v_session.price_currency, 'pending'
  );

  update public.sessions set booked_count = booked_count + 1 where id = p_session_id;

  return query
  select v_booking_id, v_cancel_token, v_merchant_uid, v_amount, v_expires;
end;
$function$;
